<project>
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.0.6</version>
		<relativePath/>
	</parent>

	<groupId>com.example</groupId>
	<artifactId>sejmstream</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>sejmstream</name>
	<description>SejmStream monorepo root</description>

	<modules>
		<module>fun_sejmlive</module>
	</modules>
</project>
