<project>
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.example</groupId>
	<artifactId>sejmstream</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>sejmstream</name>
	<description>SejmStream monorepo root</description>

	<modules>
		<module>fun_sejmapi</module>
		<module>fun_sejmlive</module>
	</modules>
</project>
